# 服务器配置
server:
  port: 8080

# 数据库配置 (SQLite)
database:
  path: "./data/auctions.db"  # SQLite文件路径

# 区块链配置
blockchain:
  # Infura Sepolia测试网
  # rpc_url: "https://sepolia.infura.io/v3/c5daace64d64444790a8d4bdd7c027a6"
  rpc_url: "wss://sepolia.infura.io/ws/v3/c5daace64d64444790a8d4bdd7c027a6"

  # 你的NFT合约地址（在Sepolia上）
  nft_contract_address: "0x00cc95BA8ebc4F24E62b5C7596Bf94F27f5d2Ccb"
  
  # 我的nft 拍卖市场合约
  auction_contract_address: "0x31bd1bb81c9cc24de83aa1e616ae4380ebc6ff70"