# 服务器配置
server:
  port: 8080

# 数据库配置 (SQLite)
database:
  path: "./data/auctions.db"  # SQLite文件路径

# 区块链配置
blockchain:
  # Infura Sepolia测试网
  rpc_url: "https://sepolia.infura.io/v3/c5daace64d64444790a8d4bdd7c027a6"
  
  # 你的NFT合约地址（在Sepolia上）
  nft_contract_address: "0x98628036b9759Da6dE7F1516136284eBB09fA052"
  
  #chain_id: 1  # 主网为 1，测试网如 Goerli 为 5

  # 先留空或者填一个假的，因为我们先测试NFT合约
  auction_contract_address: "0x0000000000000000000000000000000000000000"